version: "3.8"



services:

  app:

    build: ./app

    container_name: app

    environment:

      - MODE=stable

      - APP_PORT=3000

    networks:

      - swiftdeploy-net

    restart: always

  nginx:

    image: nginx:latest

    container_name: nginx

    ports:

      - "8080:80"

    volumes:

      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:

      - app

    networks:

      - swiftdeploy-net

    restart: always

networks:

  swiftdeploy-net:

    driver: bridge

volumes:

  logs: